- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
    check:
      jobs:
        - refstack-client-devstack-tempestconf
        - refstack-client-devstack-tempestconf-py3
    gate:
      jobs:
        - refstack-client-devstack-tempestconf
        - refstack-client-devstack-tempestconf-py3

- job:
    name: refstack-client-devstack-tempestconf-base
    parent: devstack
    description: |
      Refstack client job for testing python-tempestconf and RefStack Integration
    required-projects:
      - openstack/refstack-client
      - openstack/tempest
      - openstack/devstack
      - openstack/python-tempestconf
    roles:
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
      - zuul: openstack/refstack-client
    run: playbooks/tempestconf-refstack-devstack.yaml
    vars:
      user: demo
      cloud_user: devstack
      test_demo: true
      cloud_admin: devstack-admin
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$

- job:
    name: refstack-client-devstack-tempestconf
    parent: refstack-client-devstack-tempestconf-base
    description: |
      Refstack client job for testing python-tempestconf and RefStack Integration
      using python2.

- job:
    name: refstack-client-devstack-tempestconf-py3
    parent: refstack-client-devstack-tempestconf-base
    description: |
      Refstack client job for testing python-tempestconf and RefStack Integration
      using python3.
    vars:
      python_3_args: -p 3
      devstack_localrc:
        USE_PYTHON3: true
