- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - refstack-client-devstack-tempestconf
        - openstack-tox-py35
    gate:
      jobs:
        - refstack-client-devstack-tempestconf
        - openstack-tox-py35

- job:
    name: refstack-client-devstack-tempestconf
    parent: devstack
    description: |
      Refstack client job for testing python-tempestconf and RefStack Integration
    required-projects:
      - openstack/refstack-client
      - openstack/tempest
      - openstack/devstack
      - openstack/python-tempestconf
    roles:
      - zuul: openstack/python-tempestconf
      - zuul: openstack/tempest
      - zuul: openstack/devstack
      - zuul: openstack/refstack-client
    run: playbooks/tempestconf-refstack-devstack.yaml
    vars:
      user: demo
      cloud_user: devstack
      test_demo: true
      cloud_admin: devstack-admin
    irrelevant-files:
      - config_tempest/tests/.*$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^.*\.rst$
